### ISSUE TITLE
Simplication of user verification function

### ISSUE THREAD

**Issue by akohli96** [utsav3/SpringMVC_webapp#1]
```java
return user.equals("Utsav")&& password.equals("password")
````
in 
https://github.com/utsav3/SpringMVC_webapp/blob/9ce28c2cafd2cd8fc3e605e6fc66b6b453c706fc/src/main/java/com/in28minutes/jee/UserValidationService.java#L5

**Comment by utsav3** [comment]
Thanks, buddy!
